# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KaufdaCli < Formula
  desc "CLI for kaufda.de local offers"
  homepage "https://github.com/mreimbold/kaufda-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    url "https://github.com/mreimbold/kaufda-cli/releases/download/v0.1.0/kaufda-cli_0.1.0_macos_universal.tar.gz"
    sha256 "efbf4ec5d03ce2858d0f781a5883310102d7c1cad42fc17f5d73708f29d77f44"

    def install
      bin.install "kaufda-cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mreimbold/kaufda-cli/releases/download/v0.1.0/kaufda-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "dab98acec845c3cb557f2ccf2d5477ec6d3e41ad9d3eeea825e25d62fc930535"
      def install
        bin.install "kaufda-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mreimbold/kaufda-cli/releases/download/v0.1.0/kaufda-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "04b39a61af1f71b7c55d658cbc68d8ca65e117fdd07821c1db627a42bb9f3fc7"
      def install
        bin.install "kaufda-cli"
      end
    end
  end

  test do
    system "#{bin}/kaufda-cli", "--version"
  end
end
