# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Terraformat < Formula
  desc "Standalone Terraform/OpenTofu formatter that goes beyond terraform fmt and tofu fmt"
  homepage "https://github.com/mreimbold/terraformat"
  version "0.1.0"
  license "MIT"

  on_macos do
    url "https://github.com/mreimbold/terraformat/releases/download/v0.1.0/terraformat_0.1.0_macos_universal.tar.gz"
    sha256 "28c996e7fdf7baf1ebd48e2ed2c645e636993ee9764a06bdc11a38e08277dcf0"

    def install
      bin.install "terraformat"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mreimbold/terraformat/releases/download/v0.1.0/terraformat_0.1.0_linux_amd64.tar.gz"
      sha256 "7a95f92277f5db5b15db2a2e8e29a15515a46cf0f583b166da19cec93425f9f4"
      def install
        bin.install "terraformat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mreimbold/terraformat/releases/download/v0.1.0/terraformat_0.1.0_linux_arm64.tar.gz"
      sha256 "28391bf38622679f02c2285f18ef4a30fe27ea86a4318e7953bbd3891d2eb82a"
      def install
        bin.install "terraformat"
      end
    end
  end

  test do
    system "#{bin}/terraformat", "--version"
  end
end
