# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WithingsCli < Formula
  desc "CLI for Withings Health API"
  homepage "https://github.com/mreimbold/withings-cli"
  version "0.1.3"
  license "MIT"

  on_macos do
    url "https://github.com/mreimbold/withings-cli/releases/download/v0.1.3/withings-cli_0.1.3_macos_universal.tar.gz"
    sha256 "529a93ea080c93d23c83c9d8b5ea6d15b858b2e00b9001402abadd02b2068013"

    def install
      bin.install "withings-cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mreimbold/withings-cli/releases/download/v0.1.3/withings-cli_0.1.3_linux_amd64.tar.gz"
      sha256 "8032291855efc395f9efa2fd7f4b81952cda773d74e2b7140c780597d75e5ebe"
      def install
        bin.install "withings-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mreimbold/withings-cli/releases/download/v0.1.3/withings-cli_0.1.3_linux_arm64.tar.gz"
      sha256 "11bbb309c5314ef444c5610f961128562f22b58fc2b12f0183d1c3f017ea8d57"
      def install
        bin.install "withings-cli"
      end
    end
  end

  test do
    system "#{bin}/withings-cli", "--version"
  end
end
